package com.university.smartcampus.common.enums;

public final class AppEnums {

    private AppEnums() {
    }

    public enum AccountStatus {
        INVITED,
        ACTIVE,
        SUSPENDED
    }

    public enum AuthDeliveryMethod {
        INVITE_EMAIL,
        LOGIN_LINK_EMAIL,
        PASSWORD_RECOVERY_EMAIL
    }

    public enum ManagerRole {
        CATALOG_MANAGER,
        BOOKING_MANAGER,
        TICKET_MANAGER
    }

    public enum StudentFaculty {
        FACULTY_OF_COMPUTING,
        FACULTY_OF_ENGINEERING,
        SLIIT_BUSINESS_SCHOOL,
        FACULTY_OF_HUMANITIES_AND_SCIENCES,
        SCHOOL_OF_ARCHITECTURE,
        WILLIAM_ANGLISS_AT_SLIIT,
        FACULTY_OF_GRADUATE_STUDIES_AND_RESEARCH
    }

    public enum StudentProgram {
        BSC_HONS_INFORMATION_TECHNOLOGY(StudentFaculty.FACULTY_OF_COMPUTING),
        BSC_HONS_COMPUTER_SCIENCE(StudentFaculty.FACULTY_OF_COMPUTING),
        BSC_HONS_COMPUTER_SYSTEMS_ENGINEERING(StudentFaculty.FACULTY_OF_COMPUTING),
        BSC_HONS_IT_ARTIFICIAL_INTELLIGENCE(StudentFaculty.FACULTY_OF_COMPUTING),
        BSC_HONS_IT_SOFTWARE_ENGINEERING(StudentFaculty.FACULTY_OF_COMPUTING),
        BSC_HONS_IT_COMPUTER_SYSTEMS_NETWORK_ENGINEERING(StudentFaculty.FACULTY_OF_COMPUTING),
        BSC_HONS_IT_INFORMATION_SYSTEMS_ENGINEERING(StudentFaculty.FACULTY_OF_COMPUTING),
        BSC_HONS_IT_CYBER_SECURITY(StudentFaculty.FACULTY_OF_COMPUTING),
        BSC_HONS_IT_INTERACTIVE_MEDIA(StudentFaculty.FACULTY_OF_COMPUTING),
        BSC_HONS_IT_DATA_SCIENCE(StudentFaculty.FACULTY_OF_COMPUTING),
        BSC_ENG_HONS_CIVIL_ENGINEERING(StudentFaculty.FACULTY_OF_ENGINEERING),
        BSC_ENG_HONS_ELECTRICAL_ELECTRONIC_ENGINEERING(StudentFaculty.FACULTY_OF_ENGINEERING),
        BSC_ENG_HONS_MECHANICAL_ENGINEERING(StudentFaculty.FACULTY_OF_ENGINEERING),
        BSC_ENG_HONS_MECHANICAL_ENGINEERING_MECHATRONICS(StudentFaculty.FACULTY_OF_ENGINEERING),
        BSC_ENG_HONS_MATERIALS_ENGINEERING(StudentFaculty.FACULTY_OF_ENGINEERING),
        BBA_HONS_ACCOUNTING_FINANCE(StudentFaculty.SLIIT_BUSINESS_SCHOOL),
        BBA_HONS_BUSINESS_ANALYTICS(StudentFaculty.SLIIT_BUSINESS_SCHOOL),
        BBA_HONS_HUMAN_CAPITAL_MANAGEMENT(StudentFaculty.SLIIT_BUSINESS_SCHOOL),
        BBA_HONS_MARKETING_MANAGEMENT(StudentFaculty.SLIIT_BUSINESS_SCHOOL),
        BBA_HONS_LOGISTICS_SUPPLY_CHAIN_MANAGEMENT(StudentFaculty.SLIIT_BUSINESS_SCHOOL),
        BBA_HONS_BUSINESS_MANAGEMENT(StudentFaculty.SLIIT_BUSINESS_SCHOOL),
        BBA_HONS_MANAGEMENT_INFORMATION_SYSTEMS(StudentFaculty.SLIIT_BUSINESS_SCHOOL),
        BBA_HONS_QUALITY_MANAGEMENT(StudentFaculty.SLIIT_BUSINESS_SCHOOL),
        BSC_HONS_FINANCIAL_MATHS_APPLIED_STATISTICS(StudentFaculty.FACULTY_OF_HUMANITIES_AND_SCIENCES),
        BSC_HONS_BIOTECHNOLOGY(StudentFaculty.FACULTY_OF_HUMANITIES_AND_SCIENCES),
        BSC_HONS_PSYCHOLOGY(StudentFaculty.FACULTY_OF_HUMANITIES_AND_SCIENCES),
        BSC_HONS_NURSING(StudentFaculty.FACULTY_OF_HUMANITIES_AND_SCIENCES),
        BA_HONS_ENGLISH_STUDIES(StudentFaculty.FACULTY_OF_HUMANITIES_AND_SCIENCES),
        BED_HONS_SCIENCES_ENGLISH_SOCIAL_SCIENCES_IT(StudentFaculty.FACULTY_OF_HUMANITIES_AND_SCIENCES),
        BSC_HONS_ARCHITECTURE(StudentFaculty.SCHOOL_OF_ARCHITECTURE),
        BA_HONS_INTERIOR_DESIGN(StudentFaculty.SCHOOL_OF_ARCHITECTURE),
        MSC_ARCHITECTURE(StudentFaculty.SCHOOL_OF_ARCHITECTURE),
        ADVANCED_DIPLOMA_HOSPITALITY_MANAGEMENT(StudentFaculty.WILLIAM_ANGLISS_AT_SLIIT),
        ADVANCED_DIPLOMA_TRAVEL_TOURISM_MANAGEMENT(StudentFaculty.WILLIAM_ANGLISS_AT_SLIIT),
        DIPLOMA_EVENT_MANAGEMENT(StudentFaculty.WILLIAM_ANGLISS_AT_SLIIT),
        CERTIFICATE_IV_PATISSERIE(StudentFaculty.WILLIAM_ANGLISS_AT_SLIIT),
        COMMERCIAL_COOKERY(StudentFaculty.WILLIAM_ANGLISS_AT_SLIIT),
        POSTGRADUATE_DIPLOMA_EDUCATION(StudentFaculty.FACULTY_OF_GRADUATE_STUDIES_AND_RESEARCH),
        MASTER_OF_EDUCATION(StudentFaculty.FACULTY_OF_GRADUATE_STUDIES_AND_RESEARCH),
        MASTER_BUSINESS_ADMINISTRATION(StudentFaculty.FACULTY_OF_GRADUATE_STUDIES_AND_RESEARCH),
        MSC_INFORMATION_TECHNOLOGY(StudentFaculty.FACULTY_OF_GRADUATE_STUDIES_AND_RESEARCH),
        MSC_INFORMATION_MANAGEMENT(StudentFaculty.FACULTY_OF_GRADUATE_STUDIES_AND_RESEARCH),
        MSC_INFORMATION_SYSTEMS(StudentFaculty.FACULTY_OF_GRADUATE_STUDIES_AND_RESEARCH),
        MSC_NETWORK_ENGINEERING(StudentFaculty.FACULTY_OF_GRADUATE_STUDIES_AND_RESEARCH),
        MSC_ARTIFICIAL_INTELLIGENCE(StudentFaculty.FACULTY_OF_GRADUATE_STUDIES_AND_RESEARCH);

        private final StudentFaculty faculty;

        StudentProgram(StudentFaculty faculty) {
            this.faculty = faculty;
        }

        public StudentFaculty faculty() {
            return faculty;
        }
    }

    public enum AcademicYear {
        YEAR_1,
        YEAR_2,
        YEAR_3,
        YEAR_4
    }

    public enum Semester {
        SEMESTER_1,
        SEMESTER_2
    }

    public enum UserType {
        STUDENT,
        FACULTY,
        ADMIN,
        MANAGER
    }

    public enum TicketCategory {
        ELECTRICAL,
        NETWORK,
        EQUIPMENT,
        FURNITURE,
        CLEANLINESS,
        FACILITY_DAMAGE,
        ACCESS_SECURITY,
        OTHER
    }

    public enum TicketPriority {
        LOW,
        MEDIUM,
        HIGH,
        URGENT
    }

    public enum TicketStatus {
        OPEN,
        IN_PROGRESS,
        RESOLVED,
        CLOSED,
        REJECTED
    }

    public enum AdminAction {
        USER_CREATED,
        USER_UPDATED,
        USER_SUSPENDED,
        USER_ACTIVATED,
        USER_DELETED,
        INVITE_RESENT,
        MANAGER_ROLE_CHANGED
    }
}
